-- schema.sql (criação básica de tabelas para space_economy)
CREATE TABLE IF NOT EXISTS se_state (
  id INT PRIMARY KEY NOT NULL,
  key_name VARCHAR(128) NOT NULL UNIQUE,
  value JSON NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS se_treasury (
  id INT AUTO_INCREMENT PRIMARY KEY,
  balance BIGINT NOT NULL DEFAULT 0,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS se_debts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  citizen_id VARCHAR(64) NOT NULL,
  amount BIGINT NOT NULL,
  interest_rate DECIMAL(10,4) NOT NULL DEFAULT 0.01,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  due_at TIMESTAMP NULL,
  paid_at TIMESTAMP NULL,
  status ENUM('open','paid','warranted','defaulted') NOT NULL DEFAULT 'open',
  meta JSON NULL
);

CREATE TABLE IF NOT EXISTS se_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  level VARCHAR(16),
  source VARCHAR(64),
  message TEXT,
  data JSON NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);